#!/usr/bin/env bash
# manifest.sh — Generate wiki/MANIFEST.md
# Builds the source→article map, orphan list, and backlink graph from current wiki state.
# Safe to run any time; does not call an LLM.
# Usage: ./scripts/manifest.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WIKI_DIR="$REPO_ROOT/wiki"
RAW_DIR="$REPO_ROOT/raw"
MANIFEST="$WIKI_DIR/MANIFEST.md"

WIKI_COUNT=$(find "$WIKI_DIR" -name '*.md' ! -name '_*' ! -name 'MANIFEST.md' | wc -l | tr -d ' ')
if [ "$WIKI_COUNT" -eq 0 ]; then
    echo "Error: Wiki is empty. Run compile.sh first." >&2
    exit 1
fi

echo "=== Generating MANIFEST.md ==="

# Collect all wiki articles (excluding meta files)
mapfile -t ARTICLES < <(find "$WIKI_DIR" -name '*.md' ! -name '_*' ! -name 'MANIFEST.md' | sort)
mapfile -t RAW_FILES < <(find "$RAW_DIR" -name '*.md' | sort)

{
    echo "# Wiki Manifest"
    echo ""
    echo "> Auto-generated by \`scripts/manifest.sh\`. Do not edit manually."
    echo "> Last updated: $(date -u '+%Y-%m-%d %H:%M UTC') | Articles: ${#ARTICLES[@]} | Raw files: ${#RAW_FILES[@]}"
    echo ""

    # ── Source → Article Map ──────────────────────────────────────────────────
    echo "## Source → Article Map"
    echo ""

    for article in "${ARTICLES[@]}"; do
        rel_article="${article#$REPO_ROOT/}"
        sources=$(grep -o 'raw/[^ `]*\.md' "$article" 2>/dev/null | sort -u || true)
        if [ -n "$sources" ]; then
            title=$(grep -m1 '^# ' "$article" | sed 's/^# //')
            echo "**[$title]($rel_article)**"
            while IFS= read -r src; do
                if [ -f "$REPO_ROOT/$src" ]; then
                    echo "- \`$src\` ✓"
                else
                    echo "- \`$src\` ⚠ file not found"
                fi
            done <<< "$sources"
            echo ""
        fi
    done

    # ── Unprocessed Raw Files ─────────────────────────────────────────────────
    echo "## Unprocessed Raw Files"
    echo ""
    echo "Raw files not yet referenced by any wiki article:"
    echo ""

    unprocessed=()
    for rawfile in "${RAW_FILES[@]}"; do
        rel_raw="${rawfile#$REPO_ROOT/}"
        if ! grep -rl "$rel_raw" "$WIKI_DIR" --include='*.md' &>/dev/null; then
            unprocessed+=("$rel_raw")
        fi
    done

    if [ ${#unprocessed[@]} -eq 0 ]; then
        echo "_All raw files are referenced in the wiki._"
    else
        for src in "${unprocessed[@]}"; do
            echo "- \`$src\`"
        done
    fi
    echo ""

    # ── Orphaned Articles ─────────────────────────────────────────────────────
    echo "## Orphaned Articles"
    echo ""
    echo "Wiki articles with no raw sources listed in their Sources section:"
    echo ""

    orphans=()
    for article in "${ARTICLES[@]}"; do
        rel="${article#$REPO_ROOT/}"
        # Skip meta files
        base=$(basename "$article")
        [[ "$base" == "INDEX.md" || "$base" == "GLOSSARY.md" ]] && continue
        if ! grep -q '## Sources' "$article" 2>/dev/null; then
            title=$(grep -m1 '^# ' "$article" | sed 's/^# //')
            orphans+=("[$title]($rel)")
        fi
    done

    if [ ${#orphans[@]} -eq 0 ]; then
        echo "_No orphaned articles._"
    else
        for o in "${orphans[@]}"; do
            echo "- $o"
        done
    fi
    echo ""

    # ── Backlink Graph ────────────────────────────────────────────────────────
    echo "## Backlink Graph"
    echo ""
    echo "Outbound links per article (to other wiki articles):"
    echo ""

    for article in "${ARTICLES[@]}"; do
        rel="${article#$REPO_ROOT/}"
        links=$(grep -o '([^)]*\.md)' "$article" 2>/dev/null | tr -d '()' | grep -v '^http' | sort -u || true)
        if [ -n "$links" ]; then
            title=$(grep -m1 '^# ' "$article" | sed 's/^# //')
            echo "**$title** \`($rel)\`"
            while IFS= read -r link; do
                echo "- → \`$link\`"
            done <<< "$links"
            echo ""
        fi
    done

} > "$MANIFEST"

echo "Done. See wiki/MANIFEST.md"
